config:
  target: "http://localhost:8080"
  phases:
    - duration: 60
      arrivalRate: 1
      name: Warm up (60 req per min)
    - duration: 60
      arrivalRate: 1
      rampTo: 5
      name: Ramp up load (from 60 to 300 req per min)
    - duration: 180
      arrivalRate: 5
      name: Sustained load (300 req per min)
  payload:
    path: "keyword.csv"
    fields:
      - "message"

scenarios:
  - flow:
      - get:
          url: "/crypto/sign?message={{ message }}"

