config:
  target: "http://localhost:8080"
  phases:
    - duration: 5
      arrivalRate: 5
      name: Warm up
#    - duration: 120
#      arrivalRate: 5
#      rampTo: 50
#      name: Ramp up load
#    - duration: 600
#      arrivalRate: 50
#      name: Sustained load
  payload:
    path: "keyword.csv"
    fields:
      - "message"

scenarios:
  - flow:
      - get:
          url: "/crypto/sign?message={{ message }}"

