spring:
  application:
    name: "Synthesia Tech Challenge App"
  rabbitmq:
    host: localhost
  datasource:
    url: jdbc:mariadb://localhost:3306/messagedb
    username: root
    password: funnystory
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

queue:
  requests: "requests"
  signatures: "signatures"

synthesia:
  baseWaitingUrl: "http://localhost:3000/?identifier="
  timeout: 2 # seconds

springdoc:
  api-docs:
    path: /swagger